agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
app_name = 'agents'


urlpatterns = [
path('', AgentListView.as_view(), name='agent-list'),
path('create/', AgentCreateView.as_view(), name='agent-create'),
path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
path('<int:pk>/update', AgentUpdateView.as_view(), name='agent-update'),
path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landingPage'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name = 'signup'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout')
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from leads.models import Agent

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

agents/views.py
from django.shortcuts import render, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin
# Create your views here.


class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)
    


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent-list')
    
    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.organization = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)
    

class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name="agents/agent_detail.html"
    context_object_name= 'agent'

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent_update.html'
    form_class = AgentModelForm
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

    def get_success_url(self):
        return reverse('agents:agent-list')    
    

class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent_delete.html'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

    def get_success_url(self):
        return reverse('agents:agent-list')

agents/templates/agents/agent_create.html
{%extends "base.html"%} {%block content%}
<a href="{%url 'agents:agent-list' %}">Go back to agent list</a>
<h1>Create a new agent</h1>
<form method="POST" action=".">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">submit</button>
</form>
{% endblock content%}

agents/templates/agents/agent_delete.html
{%extends "base.html"%} {%block content%}
<a href="{%url 'agents:agent-list' %}">Go back to agent list</a>
<h1>Are you sure you want to delete this agent?</h1>
<form method="POST" action="">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">Delete</button>
</form>
{% endblock content%}

agents/templates/agents/agent_detail.html
{%extends "base.html"%} {%block content%}

<section class="text-gray-600 body-font overflow-hidden">
  <a href="{%url 'agents:agent-list' %}">Go back to agent list</a>
  <div class="container px-5 py-24 flex justify-center items-center">
    <div class="lg:w-4/5 mx-auto flex flex-wrap justify-center items-center">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{agent.user.username}}
        </h1>
        <div class="flex mb-4">
          <a
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Overview</a
          >
          <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          > -->
          <a
            href="{%url 'agents:agent-update' agent.id%}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Edit Details</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">City</span>
          <span class="ml-auto text-gray-900">Houston</span>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content%}

agents/templates/agents/agent_list.html
{%extends "base.html"%} {%block content%}
<div class="flex flex-col w-[70vw]">
  <div class="p-2 w-[100%] flex justify-between items-center">
    <h1 class="text-3xl">Agent List</h1>
    <a href="{%url 'agents:agent-create'%}">Create an agent</a>
  </div>
  <hr />
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
      {% for agent in object_list%}

      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-400 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{agent.user.username}}
            </h2>
            {% comment %}
            <p class="leading-relaxed text-base">id: {{lead.id}}</p>
            <p class="leading-relaxed text-base">Age: {{lead.age}}</p>
            <p class="leading-relaxed text-base">Agent: {{lead.agent}}</p>
            {% endcomment %}
            <a
              href="{%url 'agents:agent-detail' agent.id %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >View Agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{%endblock content%}

agents/templates/agents/agent_update.html
{%extends "base.html"%} {%block content%}

<section class="text-gray-600 body-font overflow-hidden">
  <a href="{%url 'agents:agent-list' %}">Go back to agent list</a>
  <div class="container px-5 py-24 flex justify-center items-center">
    <div class="lg:w-4/5 mx-auto flex flex-wrap justify-center items-center">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{agent.user.username}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{%url 'agents:agent-detail' agent.id%}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          > -->
          <a
            href="{%url 'agents:agent-update' agent.id%}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Edit Details</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <form class="flex flex-col space-y-4" method="POST" action="">
          {%csrf_token%} {{form.as_p}}
          <button type="submit">update</button>
        </form>
        <button class="w-full text-center py-3" type="submit">
          <a href="{%url 'agents:agent-delete' agent.id%}">delete</a>
        </button>
      </div>
    </div>
  </div>
</section>

{% endblock content%}