agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
app_name = 'agents'


urlpatterns = [
path('', AgentListView.as_view(), name='agent-list'),
path('create/', AgentCreateView.as_view(), name='agent-create'),
path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
path('<int:pk>/update', AgentUpdateView.as_view(), name='agent-update'),
path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landingPage'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name = 'signup'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout')
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
path('', views.LeadListView.as_view(), name='leadList'),
path('create/', views.LeadCreateView.as_view(), name='createLead'),
path('<int:pk>/', views.LeadDetailView.as_view(), name='leadDetail'),
path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='leadUpdate'),
path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='leadDelete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DJCRM</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="flex flex-col h-[100vh] gap-y-10 justify-start items-center">
    {%include 'navbar.html'%}
    <div class="flex flex-col justify-center items-center">
      {% block content%} {%endblock content%}
    </div>
  </body>
</html>

templates/landing.html
{%extends 'base.html'%} {%block content%}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        CRM Built with Django
      </h1>
      <p class="mb-8 leading-relaxed">Manage your leads with our CRM</p>
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Button
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>
{%endblock content%}

templates/lead_create.html
{%extends "base.html"%} {%block content%}
<a href="{%url 'leads:leadList' %}">Go back to lead list</a>
<h1>Create a new lead</h1>
<form method="POST" action=".">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">submit</button>
</form>
{% endblock content%}

templates/lead_delete.html
{%extends "base.html"%} {%block content%}
<a href="{%url 'leads:leadList' %}">Go back to lead list</a>
<h1>Are you sure you want to delete this lead?</h1>
<form method="POST" action=".">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">Delete</button>
</form>
{% endblock content%}

templates/lead_detail.html
{%extends "base.html"%} {%block content%}

<section class="text-gray-600 body-font overflow-hidden">
  <a href="{%url 'leads:leadList' %}">Go back to lead list</a>
  <div class="container px-5 py-24 flex justify-center items-center">
    <div class="lg:w-4/5 mx-auto flex flex-wrap justify-center items-center ">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Overview</a
          >
          <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          > -->
          <a
            href="{%url 'leads:leadUpdate' lead.id %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Edit Details</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">City</span>
          <span class="ml-auto text-gray-900">Houston</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Assigned Agent</span>
          <span class="ml-auto text-gray-900">{{lead.agent}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone</span>
          <span class="ml-auto text-gray-900">713-231-9924</span>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- <div class="flex flex-col">
  <a href="{%url 'leads:leadList' %}">Go back to lead list</a>
  <h1 class="text-3xl">Lead details</h1>
  <h2>Name: {{lead.first_name}} {{lead.last_name}}</h2>
  <p>age: {{lead.age}}</p>
  <p>id: {{lead.id}}</p>
  <p>Assigned agent: {{lead.agent}}</p>
  <hr />
  <a href="{%url 'leads:leadUpdate' lead.id %}">Update</a>
  <a href="{%url 'leads:leadDelete' lead.id %}">Delete</a>
</div> -->
{% endblock content%}

templates/lead_list.html
{%extends "base.html"%} {%block content%}
<div class="flex flex-col w-[70vw]">
  <div class="p-2 w-[100%] flex justify-between items-center">
    <h1 class="text-3xl">Lead List</h1>
    {% if request.user.is_organisor%}
    <a href="{%url 'leads:createLead'%}">Create a lead</a>
    {%endif%}
  </div>
  <hr />
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
      {% for lead in leads%}

      <div class="p-4 w-full">
        <div
          class="flex border-2 rounded-lg border-gray-400 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow w-max">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">id: {{lead.id}}</p>
            <p class="leading-relaxed text-base">Age: {{lead.age}}</p>
            <p class="leading-relaxed text-base">Agent: {{lead.agent}}</p>
            <a
              href="{%url 'leads:leadDetail' lead.id%}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >View Lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{%endblock content%}

<!-- 
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Shooting Stars</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">The Catalyzer</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->

templates/lead_update.html
{%extends "base.html"%} {%block content%}

<section class="text-gray-600 body-font overflow-hidden">
  <a href="{%url 'leads:leadList' %}">Go back to lead list</a>
  <div class="container w-[100%] px-5 py-24 flex justify-center items-center">
    <div class="lg:w-[4/5] mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{%url 'leads:leadDetail' lead.id%}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a
            href="{%url 'leads:leadUpdate' lead.id %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Update Details</a
          >
        </div>
        <form class="flex flex-col space-y-4" method="POST" action="">
          {%csrf_token%} {{form.as_p}}
          <button type="submit">update</button>
        </form>
        <button class="w-full text-center py-3" type="submit">
          <a href="{%url 'leads:leadDelete' lead.id%}">delete</a>
        </button>
      </div>
    </div>
  </div>
</section>
<!-- <a href="{%url 'leads:leadList' %}">Go back to lead list</a>
<h1>Update a lead: {{lead.first_name}} {{lead.last_name}}</h1>
<form method="POST" action=".">
  {%csrf_token%} {{form.as_p}}
  <button type="submit">submit</button>
</form> -->
{% endblock content%}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <a
      href="{%url 'landingPage'%}"
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <span class="ml-3 text-xl">DJCRM</span>
    </a>
    <nav
      class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400 flex flex-wrap items-center text-base justify-center"
    >
      {% if request.user.is_organisor %}
      <a href="{%url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900"
        >Agents</a
      >
      {%endif%}
      <a href="{%url 'leads:leadList' %}" class="mr-5 hover:text-gray-900"
        >Leads</a
      >

      {%if not request.user.is_authenticated %}
      <a href="{%url 'signup'%}" class="mr-5 hover:text-gray-900">Sign Up</a>
      {%endif%}
    </nav>
    {%if request.user.is_authenticated %} Logged in as:
    {{request.user.username}}

    <div class="ml-4"><a href="{%url 'logout'%}">Logout</a></div>
    {%else%}
    <a
      href="{%url 'login'%}"
      class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"
    >
      Login
      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {%endif%}
  </div>
</header>